import Providers from "@/app/Providers";
import Header from '@/components/Header'
import Navbar from "@/components/Navbar";
import './globals.css'

export const metadata = {
  title: 'Imdb Demo',
  description: 'Generated by Imdb Demo',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Navbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
